### ISSUE TITLE
Bar-Chart data parsing problem

### ISSUE THREAD

**Issue by maskapsiz** [jasonshark/ng-morris#5]
I'm using ngMorris and donut chart is working very well but when I want to use bar-chart with simple data from morrisjs webpage, I get the parsing error.

Data: 
$scope.barData = [ {
                y : '2006',
                a : 100,
                b : 90
            }, {
                y : '2007',
                a : 75,
                b : 65
            }, {
                y : '2008',
                a : 50,
                b : 40
            } ];

HTML:
bar-chart bar-data='barData' bar-x='y' bar-y='["a","b"]'

Error:
"Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
.link/<@http://localhost:8080/PusulaWeb/resources/angular/ngMorris.js:22:23
Pe/this.$get</l.prototype.$digest@http://localhost:8080/PusulaWeb/resources/angular/angular.min.js:123:136
Pe/this.$get</l.prototype.$apply@http://localhost:8080/PusulaWeb/resources/angular/angular.min.js:126:56
tc/d/<@http://localhost:8080/PusulaWeb/resources/angular/angular.min.js:17:477
e@http://localhost:8080/PusulaWeb/resources/angular/angular.min.js:36:313
tc/d@http://localhost:8080/PusulaWeb/resources/angular/angular.min.js:17:1
tc@http://localhost:8080/PusulaWeb/resources/angular/angular.min.js:18:179
Jd@http://localhost:8080/PusulaWeb/resources/angular/angular.min.js:17:1
@http://localhost:8080/PusulaWeb/resources/angular/angular.min.js:249:428
n.Callbacks/j@http://localhost:8080/PusulaWeb/resources/assets/js/jquery-1.11.0.js:2:27131
n.Callbacks/k.fireWith@http://localhost:8080/PusulaWeb/resources/assets/js/jquery-1.11.0.js:2:27949
.ready@http://localhost:8080/PusulaWeb/resources/assets/js/jquery-1.11.0.js:2:29781
K@http://localhost:8080/PusulaWeb/resources/assets/js/jquery-1.11.0.js:2:30126
" angular.min.js:102
e/<() angular.min.js:102
He/this.$get</<() angular.min.js:76
Pe/this.$get</l.prototype.$digest() angular.min.js:123
Pe/this.$get</l.prototype.$apply() angular.min.js:126
tc/d/<() angular.min.js:17
e() angular.min.js:36
tc/d() angular.min.js:17
tc() angular.min.js:18
Jd() angular.min.js:17
<anonymous> angular.min.js:249
n.Callbacks/j() jquery-1.11.0.js:2
n.Callbacks/k.fireWith() jquery-1.11.0.js:2
.ready() jquery-1.11.0.js:2
K() jquery-1.11.0.js:2

**Comment by jasonshark** [comment]
Okay thank you for opening this issue! You have to add labels attribute. So in your case with the data the html needs `labels='["a","b"]'`
